apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-arch-2021-03-config
data:
    spring.datasource.url: jdbc:postgresql://postgres:5432/myapp
    management.endpoints.web.exposure.include: "prometheus"
    management.metrics.export.prometheus.enabled: "true"
    management.metrics.distribution.percentiles-histogram.http.server.requests: "true"
    management.metrics.distribution.sla.http.server.requests: "100ms,150ms,250ms,500ms,1s"
    management.metrics.enable.jvm: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: ms-arch-2021-03-secret
type: Opaque
data:
  spring.datasource.username: bXl1c2Vy
  spring.datasource.password: cGFzc3dk