apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-chart.fullname" . }}
  labels:
    app: {{ include "postgres-chart.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ include "postgres-chart.fullname" . }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-chart.fullname" . }}-statefulset
spec:
  serviceName: {{ include "postgres-chart.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-chart.fullname" . }}
    spec:
      containers:
        - name: {{ include "postgres-chart.fullname" . }}
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              value: myapp
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: passwd
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: {{ include "postgres-chart.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi